# ======== {{{name}}} BOT TEMPLATE ========
      # {{{name}}}
      - name: {{{name}}}
        type: {{{type}}}
        image: {{{image}}}
        msaSecretName: msa-secret
        config:
          Config1: ValueFromConfig1
        secrets:
          - envVar: EnvVarName
            keyVaultSecretName: Key Vault Secret Name
# ======== {{{name}}} BOT TEMPLATE END ========
        