apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: mybot
  namespace: default
status:
  deploymentId: deployment123
  configId: config456
  sPCId: spc789
spec:
  image: mybot/image:v1
  msaAppSecret: mysecret
  config:
    key1: value1
    key2: value2
  secrets:
    - envVar: ENV_VAR1
      keyVaultSecretName: secret1
    - envVar: ENV_VAR2
      keyVaultSecretName: secret2
apiVersion: innovation.bots/v1
kind: Indexer
metadata:
  name: Teste Assistant
  namespace: 
status: 
spec:
  image: Teste Assistant
  msaAppSecret: kv-bots-rd
  config:
    IndexerPrompt: Teste Assistant
    IndexerHash: Teste Assistant
  secrets:
  - envVar: MongoDbConnectionString
    keyVaultSecretName: Teste Assistant
  - envVar: OpenAiApiKey
    keyVaultSecretName: Teste Assistant


apiVersion: innovation.bots/v1
kind: Indexer
metadata:
  name: Testing
  namespace: 
status: 
spec:
  image: Testing
  msaAppSecret: kv-bots-rd
  config:
    IndexerPrompt: Testing
    IndexerHash: Testing
  secrets:
  - envVar: MongoDbConnectionString
    keyVaultSecretName: Testing
  - envVar: OpenAiApiKey
    keyVaultSecretName: Testing

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: Jarvix
  namespace: 
status: 
spec:
  image: My Assistant
  msaAppSecret: kv-bots-rd
  config:
    OPENAI_API_BASE: My Assistant
    OPENAI_API_VERSION: My Assistant
    MONGO_DB: My Assistant
  secrets:
  - envVar: MONGO_URL
    keyVaultSecretName: My Assistant
  - envVar: OPENAI_API_KEY
    keyVaultSecretName: My Assistant

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: Indexer
  namespace: 
status: 
spec:
  image: Test Encrypt
  msaAppSecret: kv-bots-rd
  config:
    IndexerPrompt: Test Encrypt
    IndexerHash: Test Encrypt
  secrets:
  - envVar: MongoDbConnectionString
    keyVaultSecretName: Unicode~gAAAAABlgc8MogGn_-ptyhX03gHNvD5gLmv95qHPw8w3R09-aDn8A5ZqUUGhsrZBo7ByKDpy7jsJr6P3VwbFdFNSx2_GaNkHjtJ06GXMCl5hgkcc3SmXfXUeUaWjasmwY8dHE2iISl5r
  - envVar: OpenAiApiKey
    keyVaultSecretName: Unicode~gAAAAABlgc8M5fPsIhUVBSDGX87bjTAASza5bgQpL9Q50vBuyvQ8296JEnaRUpWVnbTj8Jx7AIMC4kfAyHDwKB9m6bmq_qQAObeyPk1NHTk7KaOCUMa4nZetKhjJDe6WzYntGzm_pMET

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: indexer
  namespace: 
status: 
spec:
  image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.e938348
  msaAppSecret: kv-bots-rd
  config:
    OPENAI_API_BASE: https://aoa-sophie-demo.openai.azure.com/
    OPENAI_API_VERSION: 2023-09-01-preview
    OPENAI_ENV: azure
    MONGO_DB: honda-indexer
    INDEXER_HASH: H036d05b9261d4a9a8fee071cdf1c2898
    INDEXER_URL: https://llmindexer-api-ext.qa.saiapplications.com/customquery
    COMPANY_NAME: Honda
    AGENT_NAME: Hikari
    OPENAI_MODEL: gpt-35-turbo-16k
    SOURCE_ENABLE: False
  secrets:
  - envVar: MONGO_URL
    keyVaultSecretName: Unicode~gAAAAABlguKVL_-HvOUFc0lwKe3Y1KTK5SiLjKgzpnm28AWCgs-Z6k3cBbTreVg6GYXWn4r3zsxV7zCwQQatPG-HPGeHGB6zORNJ-F-rBGF2fsqoGMXagUyEeQy2BaFnyPIdb3eGlc56PR2u6_NKX11A6TsYDA2LwZ8POEXAPXv2VFpFN_925nrzHLMJG65pey0-rBTwFALHKRTx5hoRFsYbAdUXno9DD1ddTGO4tCoz8g7yqpGblO5ea2PGISoLPC_WSgeUNya6iqiz-M9aJim-6r46Tk-KiTf_PC9NPaQmNcMkRcN3Zu8Mn7j3whU5qWr-HANptfjPHq2k1AVcCnzBAcKDBjdctYxGEX0u1KX9iOUqergh0G-bKu69pgn3TsQQbwL4Nxbk
  - envVar: OPENAI_API_KEY
    keyVaultSecretName: Unicode~gAAAAABlguKVuAN2rRG5a2D917Y4s_SyprjdVIzOj743uyTRpSDCIwtr6w8KKZ9IFRd9rG5GIQ54exWARS3f--J_nKzXFztId53ljqthFjtE-00JLO-s5R0YhIya9ZF6McZrBT2oAEusaiUbL84xtjryK2houC1IFSnPpnYQWbx1_aEIm2YaXws=
  - envVar: INDEXER_API_KEY
    keyVaultSecretName: Unicode~gAAAAABlguKV-clbcouunUa0tnZgrRsTtrx_kN6FpHUw1Q2J4hk4q5LsxSNmLdXsUh9vgv_PLdL6F3VSklCUHSjn1pv3BIQK9rMSzVUsghNs5V4eMs9jIWoDmtR2oZ8yUdWyq1S9oECv8pNd3-9YOPPvtHC4VDNmNFcg4iWLrgdItWdzMB3DrdHCKVM5gfaePxJd8o611Z4V

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: App Credentials
  namespace: 
status: 
spec:
  image: Test
  msaAppSecret: kv-bots-rd
  config: {}
  secrets:
  - envVar: MicrosoftAppType
    keyVaultSecretName: Unicode~gAAAAABlhXQE7O3QP5SKo4JwOzpUwkW9m8C7ARhTZkvicYohxMwZMh92gT_FzVb05BP_4iohnFyNk2XLjzC4JH5mYR0UlYNKHESHYU2_KCm9TsJsRRpnTTw=
  - envVar: MicrosoftAppId
    keyVaultSecretName: Unicode~gAAAAABlhXQEIZw1X_BMFbM8p31_REumvv1KD5k7YS7Op-22ACeKmyQBz6lpS8mqrpttlCFKAc8um9vgL2xmVhiGluUEjMZfNe4W7kB7lsbRBXcZltLp2-ZS2Rl00PmgCEwfzt5Mn_ruT7S-rtQuhUh5cONgGhByCgJ-jS4CohP2W4PXuFRXQPA=
  - envVar: MicrosoftAppPassword
    keyVaultSecretName: Unicode~gAAAAABlhXQEsnmTxYYZeKpOksODFIk7-2cxoKav3LCKEuyBgp3OE7Jfx5g_0Ftqzot4XJbO1VPD3cJxjSAkgK-8hy60lM78Btk0ZlekoF6wlyR9Kjg9TEGGdDGS2JmpxdImcHuqX4woUP1gKs7nMJ7rqf85sCEPpMlXpfwG7gT_-rTsRP_HmJxRMVlGLxoBlze8MMO09uvO
  - envVar: MicrosoftAppTenantId
    keyVaultSecretName: Unicode~gAAAAABlhXQEvzaQy3_iUy1ZKp3i3EBg4JnlwbdGcfe40LeGz4Vo8M06gEOMkNMwFr8g6DEbR6tr5ji8rSZIMRHXuNjDBt3efmbExE4sBVDIrgkcMhIq226bEWcCDJdpaBMotQ543ne34iEGjkU_5nYy7ypeWdiZwEi-fpEXkU1UoEinO9PSM84=

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: App Credentials
  namespace: 
status: 
spec:
  image: ''
  msaAppSecret: kv-bots-rd
  config: {}
  secrets:
  - envVar: MicrosoftAppType
    keyVaultSecretName: Unicode~gAAAAABljFhcEtYxdxnSUiOKfybE7Fy5NiK178Ecq1S6epF3JZpyvCXQ9dLKN2P8PrHaK7JusrrpehE8RXo3L_krqjrwOKAab-FRjIuwg8XK5lxQwICdOxVUbAb2o-fuaFMYyjXD3hzeXwBuGWFTUkzHSFY9V8eVnwxr2hemR6hDbZbnTIHHMrY=
  - envVar: MicrosoftAppId
    keyVaultSecretName: 
  - envVar: MicrosoftAppPassword
    keyVaultSecretName: 
  - envVar: MicrosoftAppTenantId
    keyVaultSecretName: 

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: App Credentials
  namespace: 
status: 
spec:
  image: ''
  msaAppSecret: kv-bots-rd
  config: {}
  secrets:
  - envVar: MicrosoftAppType
    keyVaultSecretName: Unicode~gAAAAABljWqZ4IQf9wThiZG2qOYEhbmiJhTqzRiwuO94p3C3KBiQhjG6Hn-b2RUC7O824d8-bgpMx92B9LIqWQHAlkl3rRug9-0greZYzeCrbsHTenkv_zB4cQry78G7yauZNama5g4DjbObyw9xUwvlolyox0S3C5V9Ds7wgOcfEx694PuYnZBdVup3XN7Gb5v23A_asQLh
  - envVar: MicrosoftAppId
    keyVaultSecretName: 
  - envVar: MicrosoftAppPassword
    keyVaultSecretName: 
  - envVar: MicrosoftAppTenantId
    keyVaultSecretName: 

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: App Credentials
  namespace: 
status: 
spec:
  image: ''
  msaAppSecret: kv-bots-rd
  config: {}
  secrets:
  - envVar: MicrosoftAppType
    keyVaultSecretName: 
  - envVar: MicrosoftAppId
    keyVaultSecretName: Unicode~gAAAAABlk7AQUT5MeoCE_zF8wDZ-O5StupPnDnxDNT-sIP0r7ViML0StlKxe0mowA7vkeUp7SWYjfAOge3RtVILBL8sl0rd9fZGqdytqWVBF19YUaWh2JnVCCbCFjhVJTYRetSM7w677wc7Tafzc3ifQjLTpbbt8uHpEko3m0eCxm3gvtRxDU7I=
  - envVar: MicrosoftAppPassword
    keyVaultSecretName: Unicode~gAAAAABlk7AQK6flHhkK_G40DnV1pImyCeTgLA51wTce-2YBW59tQPsQLJc2YK9BJmvaEUU-hHD8e3YtPKuLtanmO0IsY9jNkLK45deIb_lBF7dJyU2s_tDI6wJypdhBxVp4HeerZ8s8uqvHTezezFZTfrCWf8MlPOExy44p1Ox4w8KLxnWTOG0GtLd8RxQiWO6n5uz_rPia
  - envVar: MicrosoftAppTenantId
    keyVaultSecretName: Unicode~gAAAAABlk7AQNEDbVjwTfG2rK8BzIBvzLyOHeaRU4iDzyPKWpIDPfYbLtukegps1w6YZzJ74OPL9qr612QhyaH-ngSnql9IZN94b-gboz-mcn_9YTBPhTliLyl5fTw9GpOo3sPib-nvv_RaKTXSGJlO0usdxA0qWonDnFc1QxLulB5GpdbKpJWM=

apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: App Credentials
  namespace: 
status: 
spec:
  image: ''
  msaAppSecret: kv-bots-rd
  config: {}
  secrets:
  - envVar: MicrosoftAppType
    keyVaultSecretName: Unicode~gAAAAABlk7DAh8lVHrhTCAojoTvgm39nXPe9Al0L5BMK32sVtpHZa1yXwsZvMb9_O73w40SDd20cJFuv33UOCXwoAu305nlMOB9esCt7GcuEnW8ZxgbuWxGpKko-NFo_Rvn6aXpqqfZQilwUOH9jI6CG1J6Tx449f1i1oXpzCTxP2TIdO89HghcTUpBQ-Bqu-jt0NTmVXd2e
  - envVar: MicrosoftAppId
    keyVaultSecretName: 
  - envVar: MicrosoftAppPassword
    keyVaultSecretName: 
  - envVar: MicrosoftAppTenantId
    keyVaultSecretName: 
