apiVersion: innovation.bots/v1
kind: BotEntity
metadata:
  name: mybot
  namespace: default
status:
  deploymentId: deployment123
  configId: config456
  sPCId: spc789
spec:
  image: mybot/image:v1
  msaAppSecret: mysecret
  config:
    key1: value1
    key2: value2
  secrets:
    - envVar: ENV_VAR1
      keyVaultSecretName: secret1
    - envVar: ENV_VAR2
      keyVaultSecretName: secret2