sai-bot-framework:
  global:
    azureTenantId: 123456789012345678901234567890
    keyvaultName: kv-bots-rd

    identity:
      resourceId: /subscriptions/123456789012345678901234567890/resourcegroups/rg-bots-rd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-bots-rd
      clientId: 123456789012345678901234567890
      name: id-bots-rd

  connector:
    publicAccess:
      domain: rd-bots.qa.saiapplications.com
      environment: qa

  proactive:
    enabled: true
    publicAccess:
      domain: rd-bots-proactive.qa.saiapplications.com
      environment: qa
    mongo:
      emailStore:
        mongoUrlSecret: mongo-connstring
    config:
      ApiKey: 123456789012345678901234567890
    bots:
      # ======== BOT TEMPLATE ========
      # AF Assistant
      - name: string
        type: indexer
        image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
        msaSecretName: af-qa-app-credentials
        config:
          OPENAI_API_BASE: "https://aoa-sophie-demo.openai.azure.com/"
          OPENAI_API_VERSION: "2023-09-01-preview"
          OPENAI_ENV: azure
          MONGO_DB: string
          INDEXER_HASH: string
          INDEXER_URL: "https://llmindexer-api.qa.saiapplications.com/customquery"
          AGENT_NAME: string
          OPENAI_MODEL: gpt-35-turbo-16k
          PROMPT_COLLECTION: prompts
          SOURCE_ENABLE: "False"
        secrets:
          - envVar: MONGO_URL
            keyVaultSecretName: mongo-connstring
          - envVar: OPENAI_API_KEY
            keyVaultSecretName: openai-demo-azure-key
          - envVar: INDEXER_API_KEY
            keyVaultSecretName: string
      # ============================

# ======== teste BOT TEMPLATE ========
      # AF Assistant
      - name: teste
        type: indexer
        image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
        msaSecretName: af-qa-app-credentials
        config:
          OPENAI_API_BASE: "https://aoa-sophie-demo.openai.azure.com/"
          OPENAI_API_VERSION: "2023-09-01-preview"
          OPENAI_ENV: azure
          MONGO_DB: teste}
          INDEXER_HASH: testeupdate123
          INDEXER_URL: "https://llmindexer-api.qa.saiapplications.com/customquery"
          AGENT_NAME: teste
          OPENAI_MODEL: gpt-35-turbo-16k
          PROMPT_COLLECTION: prompts
          SOURCE_ENABLE: "False"
        secrets:
          - envVar: MONGO_URL
            keyVaultSecretName: mongo-connstring
          - envVar: OPENAI_API_KEY
            keyVaultSecretName: openai-demo-azure-key
          - envVar: INDEXER_API_KEY
            keyVaultSecretName: teste
      # ======== teste BOT TEMPLATE END ========
        
        
# ======== string BOT TEMPLATE ========
      # AF Assistant
      - name: string
        type: indexer
        image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
        msaSecretName: af-qa-app-credentials
        config:
          OPENAI_API_BASE: "https://aoa-sophie-demo.openai.azure.com/"
          OPENAI_API_VERSION: "2023-09-01-preview"
          OPENAI_ENV: azure
          MONGO_DB: string}
          INDEXER_HASH: stringupdated123
          INDEXER_URL: "https://llmindexer-api.qa.saiapplications.com/customquery"
          AGENT_NAME: string
          OPENAI_MODEL: gpt-35-turbo-16k
          PROMPT_COLLECTION: prompts
          SOURCE_ENABLE: "False"
        secrets:
          - envVar: MONGO_URL
            keyVaultSecretName: mongo-connstring
          - envVar: OPENAI_API_KEY
            keyVaultSecretName: openai-demo-azure-key
          - envVar: INDEXER_API_KEY
            keyVaultSecretName: string
      # ======== string BOT TEMPLATE END ========
        
        

# ======== 123123123123 BOT TEMPLATE ========
      # AF Assistant
      - name: 123123123123
        type: indexer
        image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
        msaSecretName: af-qa-app-credentials
        config:
          OPENAI_API_BASE: "https://aoa-sophie-demo.openai.azure.com/"
          OPENAI_API_VERSION: "2023-09-01-preview"
          OPENAI_ENV: azure
          MONGO_DB: 123123123123}
          INDEXER_HASH: 123123123123
          INDEXER_URL: "https://llmindexer-api.qa.saiapplications.com/customquery"
          AGENT_NAME: 123123123123
          OPENAI_MODEL: gpt-35-turbo-16k
          PROMPT_COLLECTION: prompts
          SOURCE_ENABLE: "False"
        secrets:
          - envVar: MONGO_URL
            keyVaultSecretName: mongo-connstring
          - envVar: OPENAI_API_KEY
            keyVaultSecretName: openai-demo-azure-key
          - envVar: INDEXER_API_KEY
            keyVaultSecretName: 123123123123
      # ======== 123123123123 BOT TEMPLATE END ========
        

# ======== 123123123123 BOT TEMPLATE ========
      # AF Assistant
      - name: 123123123123
        type: indexer
        image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
        msaSecretName: af-qa-app-credentials
        config:
          OPENAI_API_BASE: "https://aoa-sophie-demo.openai.azure.com/"
          OPENAI_API_VERSION: "2023-09-01-preview"
          OPENAI_ENV: azure
          MONGO_DB: 123123123123}
          INDEXER_HASH: indexer123update1
          INDEXER_URL: "https://llmindexer-api.qa.saiapplications.com/customquery"
          AGENT_NAME: 123123123123
          OPENAI_MODEL: gpt-35-turbo-16k
          PROMPT_COLLECTION: prompts
          SOURCE_ENABLE: "False"
        secrets:
          - envVar: MONGO_URL
            keyVaultSecretName: mongo-connstring
          - envVar: OPENAI_API_KEY
            keyVaultSecretName: openai-demo-azure-key
          - envVar: INDEXER_API_KEY
            keyVaultSecretName: 123123123123
      # ======== 123123123123 BOT TEMPLATE END ========
        

# ======== b3n21yj3126 BOT TEMPLATE ========
      # AF Assistant
      - name: b3n21yj3126
        type: indexer
        image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
        msaSecretName: af-qa-app-credentials
        config:
          OPENAI_API_BASE: "https://aoa-sophie-demo.openai.azure.com/"
          OPENAI_API_VERSION: "2023-09-01-preview"
          OPENAI_ENV: azure
          MONGO_DB: b3n21yj3126}
          INDEXER_HASH: b3n21yj3126
          INDEXER_URL: "https://llmindexer-api.qa.saiapplications.com/customquery"
          AGENT_NAME: b3n21yj3126
          OPENAI_MODEL: gpt-35-turbo-16k
          PROMPT_COLLECTION: prompts
          SOURCE_ENABLE: "False"
        secrets:
          - envVar: MONGO_URL
            keyVaultSecretName: mongo-connstring
          - envVar: OPENAI_API_KEY
            keyVaultSecretName: openai-demo-azure-key
          - envVar: INDEXER_API_KEY
            keyVaultSecretName: b3n21yj3126
      # ======== b3n21yj3126 BOT TEMPLATE END ========
        
        


        
        

# ======== shauhsuahushuahuas BOT TEMPLATE ========
      # AF Assistant
      - name: shauhsuahushuahuas
        type: indexer
        image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
        msaSecretName: af-qa-app-credentials
        config:
          OPENAI_API_BASE: "https://aoa-sophie-demo.openai.azure.com/"
          OPENAI_API_VERSION: "2023-09-01-preview"
          OPENAI_ENV: azure
          MONGO_DB: shauhsuahushuahuas}
          INDEXER_HASH: shauhsuahushuahuas
          INDEXER_URL: "https://llmindexer-api.qa.saiapplications.com/customquery"
          AGENT_NAME: shauhsuahushuahuas
          OPENAI_MODEL: gpt-35-turbo-16k
          PROMPT_COLLECTION: prompts
          SOURCE_ENABLE: "False"
        secrets:
          - envVar: MONGO_URL
            keyVaultSecretName: mongo-connstring
          - envVar: OPENAI_API_KEY
            keyVaultSecretName: openai-demo-azure-key
          - envVar: INDEXER_API_KEY
            keyVaultSecretName: shauhsuahushuahuas
      # ======== shauhsuahushuahuas BOT TEMPLATE END ========
        