sai-bot-framework:
  global:
    azureTenantId: 123456789012345678901234567890
    keyvaultName: kv-bots-rd
    identity:
      resourceId: /subscriptions/123456789012345678901234567890/resourcegroups/rg-bots-rd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-bots-rd
      clientId: 123456789012345678901234567890
      name: id-bots-rd
  connector:
    publicAccess:
      domain: rd-bots.qa.saiapplications.com
      environment: qa
  proactive:
    enabled: true
    publicAccess:
      domain: rd-bots-proactive.qa.saiapplications.com
      environment: qa
    mongo:
      emailStore:
        mongoUrlSecret: mongo-connstring
    config:
      ApiKey: 123456789012345678901234567890
    bots:
    - name: string
      type: indexer
      image: acrapplications.azurecr.io/sai-bot-framework/indexer:0.0.31.12345
      msaSecretName: af-qa-app-credentials
      config:
        OPENAI_API_BASE: https://aoa-sophie-demo.openai.azure.com/
        OPENAI_API_VERSION: 2023-09-01-preview
        OPENAI_ENV: azure
        MONGO_DB: string
        INDEXER_HASH: string
        INDEXER_URL: https://llmindexer-api.qa.saiapplications.com/customquery
        AGENT_NAME: string
        OPENAI_MODEL: gpt-35-turbo-16k
        PROMPT_COLLECTION: prompts
        SOURCE_ENABLE: False
      secrets:
      - envVar: MONGO_URL
        keyVaultSecretName: mongo-connstring
      - envVar: OPENAI_API_KEY
        keyVaultSecretName: openai-demo-azure-key
      - envVar: INDEXER_API_KEY
        keyVaultSecretName: string
assistantId: 6577751e1c476fd05b86a356
assistantName: Bot test

# ======== Bot test BOT TEMPLATE ========
      # Bot test
      - name: Bot test
        type: Indexer
        image: Bot test
        msaSecretName: msa-secret
        config:
          
            IndexerPrompt: Bot test

            IndexerHash: Bot test
        secrets:
          
          - envVar: MongoDbConnectionString
            keyVaultSecretName: Bot test

          - envVar: OpenAiApiKey
            keyVaultSecretName: Bot test
# ======== Bot test BOT TEMPLATE END ========

# ======== hahahahaha BOT TEMPLATE ========
      # hahahahaha
      - name: hahahahaha
        type: Indexer
        image: hahahahaha
        msaSecretName: msa-secret
        config:
          IndexerPrompt: hahahahaha
IndexerHash: hahahahaha
        secrets:
          - envVar: MongoDbConnectionString
            keyVaultSecretName: hahahahaha
- envVar: OpenAiApiKey
            keyVaultSecretName: hahahahaha
# ======== hahahahaha BOT TEMPLATE END ========

# ======== lelelelele BOT TEMPLATE ========
      # lelelelele
      - name: lelelelele
        type: Indexer
        image: lelelelele
        msaSecretName: msa-secret
        config:
          
            IndexerPrompt: lelelelele

            IndexerHash: lelelelele
        secrets:
          
            - envVar: MongoDbConnectionString
            keyVaultSecretName: lelelelele

            - envVar: OpenAiApiKey
            keyVaultSecretName: lelelelele
# ======== lelelelele BOT TEMPLATE END ========

# ======== kkkkkkkkkkkkkk BOT TEMPLATE ========
      # kkkkkkkkkkkkkk
      - name: kkkkkkkkkkkkkk
        type: Indexer
        image: kkkkkkkkkkkkkk
        msaSecretName: msa-secret
        config:{0}        secrets:{1}
# ======== kkkkkkkkkkkkkk BOT TEMPLATE END ========

# ======== rsrsrsrs BOT TEMPLATE ========
      # rsrsrsrs
      - name: rsrsrsrs
        type: Indexer
        image: rsrsrsrs
        msaSecretName: msa-secret
        config:IndexerPrompt: rsrsrsrs
          IndexerHash: rsrsrsrs
        secrets:- envVar: MongoDbConnectionString
            keyVaultSecretName: rsrsrsrs
          - envVar: OpenAiApiKey
            keyVaultSecretName: rsrsrsrs
# ======== rsrsrsrs BOT TEMPLATE END ========

# ======== jdsidjisjdi BOT TEMPLATE ========
      # jdsidjisjdi
      - name: jdsidjisjdi
        type: Indexer
        image: jdsidjisjdi
        msaSecretName: msa-secret
        config:
            IndexerPrompt: jdsidjisjdi
          IndexerHash: jdsidjisjdi
        secrets:
            - envVar: MongoDbConnectionString
            keyVaultSecretName: jdsidjisjdi
          - envVar: OpenAiApiKey
            keyVaultSecretName: jdsidjisjdi
# ======== jdsidjisjdi BOT TEMPLATE END ========

# ======== huehuehue BOT TEMPLATE ========
      # huehuehue
      - name: huehuehue
        type: Indexer
        image: huehuehue
        msaSecretName: msa-secret
        config:
        IndexerPrompt: huehuehue
          IndexerHash: huehuehue
        secrets:
        - envVar: MongoDbConnectionString
            keyVaultSecretName: huehuehue
          - envVar: OpenAiApiKey
            keyVaultSecretName: huehuehue
# ======== huehuehue BOT TEMPLATE END ========

# ======== lalalalalala BOT TEMPLATE ========
      # lalalalalala
      - name: lalalalalala
        type: Indexer
        image: lalalalalala
        msaSecretName: msa-secret
        config:
            IndexerPrompt: lalalalalala
          IndexerHash: lalalalalala
        secrets:
            - envVar: MongoDbConnectionString
            keyVaultSecretName: lalalalalala
          - envVar: OpenAiApiKey
            keyVaultSecretName: lalalalalala
# ======== lalalalalala BOT TEMPLATE END ========

# ======== haha BOT TEMPLATE ========
      # haha
      - name: haha
        type: Indexer
        image: haha
        msaSecretName: msa-secret
        config:
            
          IndexerPrompt: haha

          IndexerHash: haha
        secrets:
            
          - envVar: MongoDbConnectionString
            keyVaultSecretName: haha

          - envVar: OpenAiApiKey
            keyVaultSecretName: haha
# ======== haha BOT TEMPLATE END ========
